"""services.notify.base — Notifier 抽象基类 + 事件模型."""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, Optional


@dataclass
class NotificationEvent:
    """通知事件."""
    kind: str  # "hitl" | "blocked" | "approved" | "defer"
    context_id: str = ""
    customer: str = ""
    verdict: str = ""
    quote: Dict[str, Any] = field(default_factory=dict)
    reason: str = ""
    action_required: str = ""
    extra: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "kind": self.kind,
            "context_id": self.context_id,
            "customer": self.customer,
            "verdict": self.verdict,
            "quote": self.quote,
            "reason": self.reason,
            "action_required": self.action_required,
            "extra": self.extra,
        }


class NotifierBase(ABC):
    """通知器抽象基类."""

    def __init__(self, name: str = "base"):
        self.name = name

    @abstractmethod
    def send(self, event: NotificationEvent) -> bool:
        """发送单条通知. 成功返 True, 失败返 False (不抛错)."""

    def send_safe(self, event: NotificationEvent) -> bool:
        """包装 send 防止异常抛出."""
        try:
            return self.send(event)
        except Exception as e:
            import logging
            logging.getLogger(__name__).warning("[notify:%s] exception: %r", self.name, e)
            return False


def build_default_template(event: NotificationEvent) -> str:
    """构造默认通知模板 (Markdown 格式, 同时适配 Telegram / Email / Slack)."""
    quote = event.quote or {}
    unit = quote.get("unit_price", "?")
    total = quote.get("final_price") or quote.get("total_price", "?")
    cur = quote.get("currency", "CNY")

    icon = {"hitl": "🛡", "blocked": "🚫", "approved": "✅", "defer": "⏸"}.get(event.kind, "📨")

    md = (
        f"{icon} **Union Export Agent · {event.kind.upper()}**\n\n"
        f"**Context ID**: `{event.context_id}`\n"
        f"**Customer**: {event.customer}\n"
        f"**Verdict**: {event.verdict}\n"
        f"**Quote**: {cur} {unit} × qty = **{cur} {total}**\n\n"
    )
    if event.reason:
        md += f"**Reason**: {event.reason}\n"
    if event.action_required:
        md += f"\n**Action Required**: {event.action_required}\n"
    md += "\n— auto-generated by MailOrchestrator (v5.0.0 L3)"
    return md
